GET https://localhost:5062/api/users/get-decoded-token-test/eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NSIsIm5hbWUiOiJ0ZXN0X3Rlc3QiLCJuYmYiOjE3MTg4MDkwNjUsImV4cCI6MTcxODg5NTQ2NSwiaWF0IjoxNzE4ODA5MDY1LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MjE3IiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIxNyJ9.Xd09BVyOBYVjjb7uXFSAquhS9DaXSGauVraMUC8jnz5gCjGdvC3fGSV-POHY37BIWofqP6N0SGdUN8uHziyQUCPe4WWOT2hH105NXg5P0UeScjz6fhLO3N-DHfeDslwNYmIG_Btpkv9Xt0OTDAFLOBsrvUMf_xQKvaFTECVE5WuAwRYDEu6i99E_x01dpm_mrv6ao8N1XNQaGOgVu4_GGWg_na6fElIIb8TGscsrj8HhmnoKbjS9U73woQpkct_02I6mnuJjyZVvGZr2vaawQCWjPckCodi-ZqtTo6T8JLm_Z9NADAJOL3L1EftW4Xe3pdIfl3E1Z9MAEras_6c1AQ