POST http://localhost:5062/api/users
Content-Type: application/json

{
  "Name": "mytest3",
  "Email": "tes2@te42",
  "Password_hash": "test"
}

###
GET http://localhost:5062/api/users/22
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMiIsIm5hbWUiOiJteXRlc3QzIiwibmJmIjoxNzE4NDA1ODQ0LCJleHAiOjE3MTg0MDc2NDQsImlhdCI6MTcxODQwNTg0NCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIxNyIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyMTcifQ.fkC7ZdUD_rO0JNlE2VLRWW7fbZkSdVuPYwvXzI3z8Gab3r46ZFOV4hlE810K2jLiRZb4Hzu15rDZZn_TPL3Nupyhi5eNy8qnpSY6qjTTw4MdNsCiiVCWYebyckrDE106F1EwLqIRtYGzKq-FbC1acJvrX1D_hxl0UOR3y3q3SIvRKMUZbQ7M06vq67e-vGShETGaq4ySU6H7MvELgXxi1I57wEXUsInUD3XSxYGHWyWPFJj89VC0Rny9MZqOpXt9zpAoXgKHewY1SjAYJ7iGFHq9Wu_-mG2W4umEGx7jMMzjyHOapNu4v9JI-bfcX0xNSlQ-9ww01torTRedY3yx9g

###
PUT http://localhost:5062/api/users/17
Content-Type: application/json

{
  "Name": null,
  "Email": "tes2@tesupdate2",
  "Password_hash": null
}

###
DELETE http://localhost:5062/api/users/17

###
GET http://localhost:5062/api/users/GetToken/22