POST https://localhost:7217/api/images
Content-Type: application/json

{
    "Added_by_user": 45,
    "Extension": "jpg"
}

###
GET https://localhost:7217/api/images/45

###
PUT https://localhost:7217/api/images/44
Content-Type: application/json

{
    "Added_by_user": 45,
    "Extension": "png"
}

###
DELETE https://localhost:7217/api/images/1